source:
  path: "hdfs:///user/gman/ds-jedai/LINEARWATER.tsv"
  realIdField: "2"
  geometryField: "0"

target:
  path: "hdfs:///user/gman/ds-jedai/AREAWATER.tsv"
  realIdField: "2"
  geometryField: "0"

relation: "DE9IM"

configurations:
  thetaGranularity: "avg"
  gridType: "QUADTREE"
  progressiveAlgorithm: "SUPERVISED"
  partitions: "400"
  num_iterations: "5"
  budget: "10000"
